[package]
name = "cy-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
clap = { version = "4.4.11", features = ["derive"] }
parquet = { version = "49.0.0", default-features = false, features = ["zstd"] }
regex = "1.10.2"
