[project]
name = "hugging-face-upload"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"

dependencies = ["huggingface-hub", "requests", "datasets"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
